name: Build Test
description: 'Build Test'

inputs:
  json-payload:
    description: 'Test'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Build Test
      shell: bash
      run: |
        echo "Test : ${{ inputs.json-payload }}"