name: Build Test
description: 'Build Test'

inputs:
  json-payload:
    description: 'Test'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Build Test
      shell: bash
      run: |
        echo "Test : ${{ env.TEST }}"
        echo "Test : $TEST"
        echo '${{ fromJson(inputs.json-payload).build-aab != null && fromJson(inputs.json-payload).build-aab || fromJson(inputs.json-payload).is-deploy != null && fromJson(inputs.json-payload).is-deploy }}'