name: Build Test
description: 'Build Test'

inputs:
  json-payload:
    description: 'Test'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Build Test
      shell: bash
      run: |
        echo "Android : ${{ fromJson(inputs.json-payload).android }}"
        echo "Common : ${{ fromJson(inputs.json-payload).common }}"