name: Build package

on:
  workflow_dispatch:

jobs:
  build:
    uses: homapf/shared-workflows/.github/workflows/build-package.yml@master
    with:
      build-method: "Build.CreateAllEmbeddedUnityPackages"
      bare-repository: true
    secrets: inherit
