name: Test Matrix

on:
  workflow_call:
    inputs:
      platform-matrix:
        description: 'Test platform matrix'
        default: '[ "macOS", "iOS", "tvOS", "watchOS" ]'
        required: false
        type: string

jobs:
  test:
    name: Test for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        targetPlatform: ${{ fromJson(inputs.platform-matrix) }}
    steps:
      - name: Log test platform
        run: |
          echo "Test platform: ${{ matrix.targetPlatform }}"