
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: step1
        continue-on-error: true
        shell: bash
        run: |
          echo "Step 1"
          exit 1
      - name: Sleep for Retry
        if: ${{ steps.step1.outcome == 'failure' }}
        run: |
          sleep 60
      - name: Step 2
        id: step2
        shell: bash
        run: |
          echo "Step 2"