name: Bot Tests

on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      string: ${{ steps.output.outputs.string }}
    steps:
      - name: Output multiline string
        id: output
        run: |
          test='hello
          world'
          echo "string=$test" >> "$GITHUB_OUTPUT"
  test:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Echo string
        run: echo "${{ needs.first.outputs.string }}"