
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      should-run-first-job:
        description: 'Should run first job'
        required: true
        default: true
        type: boolean
        
jobs:
  first-job:
    runs-on: ubuntu-latest
    if: ${{ inputs.should-run-first-job }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run first job
        run: |
          sleep 10 
          echo "First job"
        
  second-job:
    runs-on: ubuntu-latest
    if: !cancelled()
    needs: first-job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run second job
        run: |
          sleep 10 
          echo "Second job"