name: Bot Tests

on:
  workflow_dispatch:
    inputs:
      build-aab:
        description: 'Build AAB'
        required: false
        default: 'false'
      is-deploy:
        description: 'Is Deploy'
        required: false
        default: 'false'

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Output multiline string
        id: output
        run: |
          echo "${{ (inputs.build-aab == 'true' || inputs.is-deploy == 'true') && 'true' || 'false' }}"