
name: Dispatch Tests
on:
  workflow_dispatch:
        
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        shell: bash
        run: |
          echo "Hello World"
  main-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    needs: first-job
    steps:
      - name: Step 2
        shell: bash
        run: |
          gh run view ${{ github.run_id }} --repo ${{ github.repository }} --log-failed