name: Run Unity

on:
  workflow_dispatch:
    inputs:
      json-payload:
        description: 'Test'
        required: true
        default: '{"android": {"build": "true"}}'
  
jobs:
  run-unity:
    runs-on: ubuntu-latest

    name: Run Unity
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        shell: bash
        run: echo ${{ fromJson(inputs.json-payload).android.build }}