
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: string
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        if: ${{ inputs.test }}
        shell: bash
        run: |
          echo "Step 1"