
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Prints input
        shell: bash
        run: |
          echo ${{ fromJson(inputs.json).development-mode == null }}
          echo ${{ fromJson(inputs.json).development-mode }}
          echo ${{ (fromJson(inputs.json).development-mode == null) && 'false' || fromJson(inputs.json).development-mode }}