name: Run Unity

on:
  workflow_dispatch:
  
jobs:
  run-unity:
    runs-on: ubuntu-latest

    name: Run Unity
    steps:
      - name: Test1
        env:
          TEST: "Hello World"
        shell: bash
        run: |
          echo $TEST
      - name: Test2
        shell: bash
        run: |
          echo $TEST