name: Run Unity

on:
  workflow_dispatch:
  
jobs:
  run-unity:
    runs-on: ubuntu-latest

    name: Run Unity
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        env:
          TEST: "Hello World"
        uses: ./