
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      development-mode:
        description: 'Development mode'
        required: true
        default: false
        type: boolean
      build-type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
          - 'Release'
          - 'Development'
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          echo ${{ (inputs.development-mode == true && inputs.build-type != 'Release') && 'true' || 'false' }}