name: Bot Tests

on:
  workflow_dispatch:
    inputs:
      string:
        description: 'Test string'
        required: true
        default: 'Something'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo string
        run: echo ${{ github.event.inputs.string }}