name: Run Unity

on:
  workflow_dispatch:
  
jobs:
  run-unity:
    strategy:
      matrix:
        unityVersion: [2022.3.24f1, 2021.3.40f1]
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-${{ matrix.unityVersion }}-linux-il2cpp-3

    name: Run Unity
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Unity
        run: unity-editor -batchmode -nographics -logFile /dev/stdout -projectPath . -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -serial ${{ secrets.UNITY_SERIAL }} -quit
      
      - name: Return License
        if: always()
        run: unity-editor -logFile /dev/stdout -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -quit -returnlicense