
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Prints input
        shell: bash
        run: |
          echo ${{ fromJson(inputs.json).development-mode != null && fromJson(inputs.json).development-mode }}
          ${{ fromJson(inputs.json).rollout-percentage == null && 0.5 || fromJson(inputs.json).rollout-percentage }}