name: Run Unity

on:
  workflow_dispatch:
    inputs:
      json-payload:
        description: 'Test'
        required: true
        default: '{"android": {"build": "true"}, "common": {"version": "42"}}'
  
jobs:
  run-unity:
    runs-on: ubuntu-latest

    name: Run Unity
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: ./
        with:
          json-payload: ${{ fromJson(inputs.json-payload.build) }}