
name: Dispatch Tests
on:
  workflow_dispatch:
        
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        shell: bash
        run: |
          echo "Hello World"
          echo "job_id=${{ github.job }}" >> $GITHUB_ENV
  main-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    needs: first-job
    steps:
      - name: Step 2
        shell: bash
        run: |
          echo "The job_id from the build job is ${{ needs.first-job.outputs.job_id }}"
          gh run view ${{ github.run_id }} --repo ${{ github.repository }} --log-failed --job ${{ needs.first-job.outputs.job_id }}"