
name: Dispatch Tests
on:
  workflow_dispatch:
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Step 1
        shell: bash
        run: |
          gh run view ${{ github.run_id }} --repo ${{ github.repository }}