name: Bot Tests

on:
  workflow_dispatch:
    inputs:
      build-aab:
        description: 'Build AAB'
        required: false
        default: 'false'
      is-deploy:
        description: 'Is Deploy'
        required: false
        default: 'false'

jobs:
  first:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ toJson(inputs) }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Reusable action
        uses: ./
        with:
          json-payload: ${{ toJson(inputs) }}
        