
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      run_first_job:
        description: 'Run the first job'
        required: false
        default: 'false'
        
jobs:
  first-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_first_job == 'true' }}
    steps:
      - name: Step 1
        shell: bash
        run: |
          echo "Hello World"
          exit 1
  main-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    needs: first-job
    if: always() && needs.first-job.result != 'failure'
    steps:
      - name: Step 2
        shell: bash
        run: |
          echo "Hello World 2"