
name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      development-mode:
        description: 'Development mode'
        required: true
        default: false
        type: boolean
      build-type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
          - 'Release'
          - 'Development'
      platform:
        description: 'Platform'
        required: true
        default: 'Android'
        type: choice
        options:
          - 'Android'
          - 'iOS'
      track:
        description: 'Track'
        required: true
        default: 'production'
        type: choice
        options:
          - 'production'
          - 'internal'
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          echo ${{ ( (inputs.platform == 'Android' && inputs.build-type == 'Release') || (inputs.platform == 'iOS' && inputs.track == 'production' ) ) && 'false' || inputs.development-mode }}