name: Builds - Ubuntu

on:
  workflow_dispatch:

jobs:
  buildForAllPlatformsUbuntu:
    name: ${{ matrix.targetPlatform }} on ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        providerStrategy:
          # - local-docker
          - local
        projectPath:
          - test-project
        unityVersion:
          - 2021.3.32f1
          - 2022.3.13f1
          - 2023.2.2f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit) with mono backend.
          - StandaloneWindows64 # Build a Windows 64-bit standalone with mono backend.
          - StandaloneLinux64 # Build a Linux 64-bit standalone with mono/il2cpp backend.
          - iOS # Build an iOS project.
          - Android # Build an Android .apk.
          - WebGL # WebGL.
        buildWithIl2cpp:
          - false
          - true
        additionalParameters:
          - -param value
          - -standaloneBuildSubtarget Server
        # Skipping configurations that are not supported
        exclude:
          # No il2cpp support on Linux Host
          - targetPlatform: StandaloneOSX
            buildWithIl2cpp: true
          - targetPlatform: StandaloneWindows64
            buildWithIl2cpp: true
          # Only builds with Il2cpp
          - targetPlatform: iOS
            buildWithIl2cpp: false
          - targetPlatform: Android
            buildWithIl2cpp: false
          - targetPlatform: WebGL
            buildWithIl2cpp: false
          # No dedicated server support
          - targetPlatform: WebGL
            additionalParameters: -standaloneBuildSubtarget Server
          - targetPlatform: Android
            additionalParameters: -standaloneBuildSubtarget Server
          - targetPlatform: iOS
            additionalParameters: -standaloneBuildSubtarget Server
          # No dedicated server support on Linux Host
          - targetPlatform: StandaloneOSX
            additionalParameters: -standaloneBuildSubtarget Server
          # No il2cpp dedicated server support on Linux Host
          - targetPlatform: StandaloneWindows64
            additionalParameters: -standaloneBuildSubtarget Server
            buildWithIl2cpp: true

    steps:
      - name: Clear Space for Android Build
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v4
        with:
          lfs: true

      ###########################
      #          Cache          #
      ###########################
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-ubuntu-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-ubuntu-
            Library-
      ###########################
      #  Set Scripting Backend  #
      ###########################
      - name: Set Scripting Backend To il2cpp
        if: matrix.buildWithIl2cpp == true
        run: |
          mv -f "./test-project/ProjectSettings/ProjectSettingsIl2cpp.asset" "./test-project/ProjectSettings/ProjectSettings.asset"
      ###########################
      #          Build          #
      ###########################
      - name: Build
        uses: ./
        id: build-1
        continue-on-error: true
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: 'GameCI Test Build'
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -profile SomeProfile -someBoolean -someValue exampleValue ${{ matrix.additionalParameters }}
          providerStrategy: ${{ matrix.providerStrategy }}
          allowDirtyBuild: true

      ###########################
      #          Upload         #
      ###########################
      - uses: actions/upload-artifact@v4
        with:
          name:
            'Build ${{ matrix.targetPlatform }} on Ubuntu (${{ matrix.unityVersion }}_il2cpp_${{ matrix.buildWithIl2cpp
            }}_params_${{ matrix.additionalParameters }})'
          path: build
          retention-days: 14