on: [workflow_dispatch]

jobs:
  inspection:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-

      - name: Solution generation
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: Android
          unityVersion: 2022.3.24f1
          versioning: None
          buildMethod: "Packages.Rider.Editor.RiderScriptEditor.SyncSolution"
          manualExit: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./workspace.sln
          solutionWideAnalysis: false
          minimumReportSeverity: warning
          minimumSeverity: warning
          include: |
            **.cs