name: Release package

on:
  release:
    types: [published]

jobs:
  tests:
    uses: homapf/shared-workflows/.github/workflows/run-tests.yml@main
    secrets: inherit
  github-release:
    uses: homapf/shared-workflows/.github/workflows/github-release.yml@main
    secrets: inherit
    needs: tests
  upm-release:
    uses: homapf/shared-workflows/.github/workflows/upm-release.yml@main
    secrets: inherit
    needs: tests
