name: Test package

on: [push, pull_request]

jobs:
  activation:
    name: Create project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout unity empty project
        uses: actions/checkout@v3
        with:
          repository: homapf/unity-empty-project

      - name: Checkout package
        uses: actions/checkout@v3
        with:
          path: Packages/my-awesome-package

      - uses: actions/cache@v2
        with:
          path: Library

      - name: Running tests
        uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts