name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Sync submodule
        run: |
          git subtree push --prefix="Packages/" origin submodule
