name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      json:
        description: 'JSON input'
        required: true
        default: '{}'
        
run-name: ${{ fromJson(inputs.json).run-name }}

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Prints input
        shell: bash
        run: |
          echo "Run name: ${{fromJson(inputs.json).run-name}}"