name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync submodule
        run: |
          git fetch origin submodule
          git checkout submodule
          git subtree pull --prefix="Packages/" origin
