name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync submodule
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: submodule
          FOLDER: Packages/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
