name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sync submodule
        run: |
          git fetch origin develop
          git checkout develop
          git subtree split --prefix "Packages/" -b submodule
          git push origin submodule
