name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync submodule
        run: |
          git --version
          git push origin --delete submodule
          git subtree push --prefix="Packages/" origin submodule
