name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync submodule
        run: |
          git subtree split -P "Packages/" -b submodule
          git push origin submodule --force
