name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ssh-key: ${{secrets.SSH}}
      - name: Sync submodule
        run: |
          git subtree push --prefix="Packages/" "https://github.com/homapf/github-actions-tests.git" submodule
