name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync submodule
        run: |
          git push origin `git subtree split --prefix "Packages/" develop`:submodule --force
