name: Dispatch Tests
on:
  workflow_dispatch:
    inputs:
      one:
        description: 'One'
        required: true
        default: 'true'
      two:
        description: 'Two'
        required: true
        default: 'Release'
        
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Prints input
        shell: bash
        run: |
          echo "Test: ${{(inputs.one == 'true' || inputs.two == 'Release') && '.aab' || '.apk'}}