name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync submodule
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git subtree push --prefix="Packages/" submodule-core
