name: Test package

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ssh-key: ${{secrets.SSH}}
      - name: Sync submodule
        run: |
          git remote rm origin
          git remote add origin "https://github.com/homapf/github-actions-tests.git"
          git config --global user.name "Admin"
          git config --global user.email "pf@homagames.com"
          git subtree push --prefix="Packages/" origin submodule
