name: Test package

on: [pull_request]

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone shared workflow
        uses: actions/checkout@v3
        with:
          repository: homapf/shared-workflows
          path: .github/workflows/shared-workflow