name: Test package

on: [pull_request]

jobs:
  tests:
    name: Testing package ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Running tests
        uses: homapf/unity-test-runner@main
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: "Android"
