name: Test

on:
  workflow_dispatch:
    inputs:
      some-input:
        description: "String input"
        required: true
        type: string

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Call
        uses: ./.github/workflows/called.yml
        with:
          platform-matrix: '[ "macOS", "iOS", "tvOS", "watchOS" ]'