name: Build without quit command test

on: [pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # Build
      - name: Build project
        uses: homagames/unity-builder@homapf/optional-quit-command
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          versioning: Semantic
          allowDirtyBuild: true
          buildName: test
          buildsPath: Build
          quit: true